spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    username: postgres
  jackson:
    property-naming-strategy: SNAKE_CASE
application:
  jwt:
    token-prefix: Bearer
    expires-in-days: 1